SSAFY-GoldMen/backend

- goldmen-common/src/main/java/com/goldmen/home/type/ClientResponse.java
> [Common] `ClientResponse` 타입 클래스 개발

- .gitignore
- goldmen-application/goldmen-batch/build.gradle
- goldmen-application/goldmen-batch/src/test/java/com/goldmen/home/BatchApplicationTest.java
- goldmen-client/seoul-client/src/main/java/com/goldmen/home/house/dto/SeoulOpenDataHouseAPIRequest.java
- goldmen-client/seoul-client/src/main/java/com/goldmen/home/house/service/SeoulOpenDataRentHouseClient.java
- goldmen-client/seoul-client/src/main/java/com/goldmen/home/house/vo/SeoulOpenDataHouse.java
- goldmen-client/seoul-client/src/main/java/com/goldmen/home/house/vo/SeoulOpenDataHouseData.java
- goldmen-client/seoul-client/src/main/java/com/goldmen/home/house/vo/SeoulOpenDataHouseWrapper.java
- goldmen-client/seoul-client/src/test/java/com/goldmen/home/SeoulClientTestConfiguration.java
- goldmen-client/seoul-client/src/test/java/com/goldmen/home/house/service/SeoulOpenDataSeoulOpenDataHouseHouseClientTest.java
- goldmen-client/seoul-client/src/test/resources/application.yml
> [Client] 서울공공데이터 집 FetchAPI

- goldmen-application/goldmen-api/src/main/java/com/goldmen/home/user/member/controller/MemberController.java
- goldmen-application/goldmen-api/src/main/java/com/goldmen/home/user/member/service/MemberService.java
- goldmen-application/goldmen-api/src/main/java/com/goldmen/home/user/message/MemberMessage.java
- goldmen-common/src/main/java/com/goldmen/home/type/ApiResponse.java
- goldmen-common/src/main/java/com/goldmen/home/type/Message.java
- #12 
---
---
- `ApiResponse` 설계 및 구현
- Message Mark Interface 생성
---
> [Common] ApiResponse Type 을 설계 및 구현

- goldmen-application/goldmen-api/src/main/java/com/goldmen/home/user/member/controller/MemberController.java
- goldmen-application/goldmen-api/src/main/java/com/goldmen/home/user/member/dto/request/MemberLoginRequest.java
- goldmen-application/goldmen-api/src/main/java/com/goldmen/home/user/member/dto/request/MemberSignupRequest.java
- goldmen-application/goldmen-api/src/main/java/com/goldmen/home/user/member/mapper/MemberMapper.java
- goldmen-application/goldmen-api/src/main/java/com/goldmen/home/user/member/service/MemberService.java
- goldmen-application/goldmen-api/src/main/java/com/goldmen/home/user/message/MemberMessage.java
- goldmen-application/goldmen-api/src/test/java/com/goldmen/home/user/member/fixture/MemberFixture.java
- goldmen-application/goldmen-api/src/test/java/com/goldmen/home/user/member/service/MemberServiceTest.java
- goldmen-common/src/main/java/com/goldmen/home/type/ApiResponse.java
- goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/user/member/domain/MemberRepository.java
- goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/user/member/service/MemberLoadService.java
- goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/user/member/service/MemberServiceImpl.java
- goldmen-domain/jpa-domain/src/test/java/com/goldmen/home/user/member/domain/MemberRepositoryTest.java
- goldmen-domain/jpa-domain/src/test/java/com/goldmen/home/user/member/fixture/MemberFixture.java
- goldmen-domain/jpa-domain/src/test/java/com/goldmen/home/user/member/service/MemberServiceImplTest.java
- #14 
---
---
- 로그인 기능 구현
- 로그인 테스트 코드 구현
---
> [Application & Domain] 로그인 기능을 구현

- goldmen-client/kakao-client/src/main/java/com/goldmen/home/dto/request/KakaoAPIRequest.java
- goldmen-client/kakao-client/src/main/java/com/goldmen/home/service/KakaoMapService.java
- goldmen-client/kakao-client/src/test/java/com/goldmen/home/service/KakaoMapServiceTest.java
> Fix(#19):KakaoAPIRequest 역할 추가

- goldmen-application/goldmen-api/src/main/java/com/goldmen/home/global/WebConfig.java
- #21 
---
---
- `WebConfig` 설정
---
> [Application] WebConfig 작성

- goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/building/Monthly/domain/Monthly.java
- goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/building/Monthly/domain/MonthlyRepository.java
- goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/building/Monthly/service/MonthlyService.java
- goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/building/building/data/cond/FindBuildingOptionCond.java
- goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/building/building/domain/BuildingRepository.java
- goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/building/building/service/BuildingService.java
- goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/building/jeonse/domain/Jeonse.java
- goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/building/jeonse/domain/JeonseRepository.java
- goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/building/jeonse/service/JeonseService.java
- goldmen-domain/jpa-domain/src/test/java/com/goldmen/home/building/building/domain/BuildingRepositoryTest.java
- goldmen-domain/jpa-domain/src/test/java/com/goldmen/home/building/building/fixture/BuildingFixture.java
- goldmen-domain/jpa-domain/src/test/java/com/goldmen/home/building/building/service/BuildingServiceTest.java
- goldmen-domain/jpa-domain/src/test/java/com/goldmen/home/map/district/domain/DistrictRepositoryTest.java
- goldmen-domain/jpa-domain/src/test/java/com/goldmen/home/map/district/fixture/DistrictFixture.java
- goldmen-domain/jpa-domain/src/test/java/com/goldmen/home/map/district/service/DistrictServiceTest.java
- goldmen-domain/jpa-domain/src/test/java/com/goldmen/home/map/legal/domain/LegalRepositoryTest.java
- goldmen-domain/jpa-domain/src/test/java/com/goldmen/home/map/legal/fixture/LegalFixture.java
- goldmen-domain/jpa-domain/src/test/java/com/goldmen/home/map/legal/service/LegalServiceTest.java
> [Domain] 집관련 도메인 모듈 서비스 구현

- goldmen-application/goldmen-batch/src/main/java/com/goldmen/home/BatchApplicationRunner.java
- goldmen-application/goldmen-batch/src/main/java/com/goldmen/home/house/service/RentHouseService.java
- goldmen-application/goldmen-batch/src/main/java/com/goldmen/home/map/service/MapService.java
- goldmen-application/goldmen-batch/src/main/java/com/goldmen/home/mapper/BatchMapper.java
- goldmen-application/goldmen-batch/src/main/java/com/goldmen/home/station/service/StationService.java
- goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/map/legal/domain/LegalRepository.java
- goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/map/legal/service/LegalService.java
- goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/metro/line/domain/Line.java
- goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/metro/line/service/LineServiceImpl.java
- goldmen-domain/jpa-domain/src/test/java/com/goldmen/home/map/legal/service/LegalServiceTest.java
> Refact(#30):Mapper 생성

- goldmen-domain/jpa-domain/build.gradle
- goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/building/building/domain/Building.java
- goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/building/building/domain/BuildingRepository.java
- goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/building/building/service/BuildingService.java
- goldmen-domain/jpa-domain/src/test/java/com/goldmen/home/building/building/domain/BuildingRepositoryMysqlTest.java
- goldmen-domain/jpa-domain/src/test/resources/application.yml
> [Domain] 역 근처 집 조회

- goldmen-application/goldmen-api/src/main/java/com/goldmen/home/building/service/BuildingEnum.java
- goldmen-application/goldmen-api/src/main/java/com/goldmen/home/building/service/HouseService.java
- goldmen-application/goldmen-api/src/main/java/com/goldmen/home/global/Mapper.java
- goldmen-application/goldmen-api/src/main/java/com/goldmen/home/metro/dto/NearMetroRequest.java
- goldmen-application/goldmen-api/src/main/java/com/goldmen/home/metro/dto/NearMetroResponse.java
- goldmen-application/goldmen-api/src/main/java/com/goldmen/home/metro/duration/controller/NearController.java
- goldmen-application/goldmen-api/src/main/java/com/goldmen/home/metro/duration/service/DurationService.java
- goldmen-application/goldmen-api/src/main/java/com/goldmen/home/metro/service/NearService.java
- goldmen-application/goldmen-api/src/main/resources/application.yml
- goldmen-application/goldmen-api/src/test/java/com/goldmen/home/metro/service/NearServiceTest.java
- goldmen-application/goldmen-batch/src/main/java/com/goldmen/home/metro/duration/service/DurationService.java
- goldmen-common/src/main/java/com/goldmen/home/mapper/PriceMapper.java
- goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/building/Monthly/domain/MonthlyRepository.java
- goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/building/Monthly/service/MonthlyService.java
- goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/building/jeonse/domain/JeonseRepository.java
- goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/building/jeonse/service/JeonseService.java
- goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/metro/duration/domain/DurationRepository.java
- goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/metro/duration/service/DurationLoadService.java
- goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/metro/duration/service/DurationServiceImpl.java
- goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/metro/station/domain/StationRepository.java
- goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/metro/station/service/StationFindService.java
- goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/metro/station/service/StationServiceImpl.java
- goldmen-domain/jpa-domain/src/test/java/com/goldmen/home/metro/duration/domain/DurationRepositoryTest.java
- goldmen-domain/jpa-domain/src/test/resources/application.yml
가까운 역 찾기 Controller, Service 추가
---
---
---
> [Applicatoin & Domain] 가까운 역 찾기 Controller, Service 추가

- goldmen-application/goldmen-api/src/main/java/com/goldmen/home/building/service/HouseService.java
- goldmen-common/src/main/java/com/goldmen/home/mapper/PriceMapper.java
resolve #45
목록이 없을 때 중앙값 못 가져오는 버그 수정
---
---
---
> [Fix] 목록이 없을 때 중앙값 못 가져오는 버그 수정

- goldmen-application/goldmen-api/src/main/java/com/goldmen/home/house/controller/HouseController.java
- goldmen-application/goldmen-api/src/main/java/com/goldmen/home/house/dto/response/GetHousePosition.java
- goldmen-application/goldmen-api/src/main/java/com/goldmen/home/house/dto/response/GetHousePositionResponse.java
- goldmen-application/goldmen-api/src/main/java/com/goldmen/home/house/service/HouseService.java
- goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/building/global/domain/Saleable.java
resolve #44
지도에 표시할 집 목록 가져오기
---
---
---
> [ Application & Doamin ] 지도에 표시할 집 목록 가져오기

- goldmen-application/goldmen-api/src/main/java/com/goldmen/home/house/controller/HouseController.java
- goldmen-application/goldmen-api/src/main/java/com/goldmen/home/house/dto/request/GetHouseRequest.java
- goldmen-application/goldmen-api/src/main/java/com/goldmen/home/house/dto/request/SaleableDetailRequest.java
- goldmen-application/goldmen-api/src/main/java/com/goldmen/home/house/dto/response/GetHouseResponse.java
- goldmen-application/goldmen-api/src/main/java/com/goldmen/home/house/dto/response/SaleableDetailResponse.java
- goldmen-application/goldmen-api/src/main/java/com/goldmen/home/house/service/HouseService.java
- goldmen-application/goldmen-api/src/main/java/com/goldmen/home/mapper/ApiMapper.java
- goldmen-application/goldmen-api/src/test/java/com/goldmen/home/house/service/HouseServiceTest.java
- goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/building/Monthly/domain/Monthly.java
- goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/building/Monthly/domain/MonthlyRepository.java
- goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/building/global/domain/PriceEnum.java
- goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/building/global/domain/Saleable.java
- goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/building/jeonse/domain/Jeonse.java
- goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/building/jeonse/domain/JeonseRepository.java
resolve #51 
매물 디테일 가져오기
---
---
---
> [Application & Domain] 매물 디테일 가져오기

- goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/metro/duration/domain/DurationRepository.java
- 가까운 역 부터 나오도록 변경
- 검색한 역 표시
- 원래됨
---
---
---
> 가까운 역 조회 기능 수정

- goldmen-application/goldmen-api/src/main/java/com/goldmen/home/global/Mapper.java
- goldmen-application/goldmen-api/src/main/java/com/goldmen/home/metro/dto/NearMetroResponse.java
역 좌표 반환 추가
resolve #53 
---
---
---
> [Application] 역 좌표 반환 추가

- goldmen-application/goldmen-api/src/main/java/com/goldmen/home/house/dto/response/GetHouseResponse.java
- goldmen-application/goldmen-api/src/main/java/com/goldmen/home/house/dto/response/SaleableDetailResponse.java
resolve #56 
매물 가격, 평수 표시 방법 변경
---
---
---
> 매물 가격, 평수 표시 방법 변경

- goldmen-application/goldmen-api/src/main/java/com/goldmen/home/house/dto/request/Area.java
> fix: request Area수정

- goldmen-application/goldmen-api/src/main/java/com/goldmen/home/house/dto/request/Area.java
집 검색 필터 버그 수정
resolve #60 
---
---
---
> 집 검색 필터 버그 수정

- goldmen-application/goldmen-api/src/main/java/com/goldmen/home/user/member/controller/MemberController.java
- goldmen-application/goldmen-api/src/main/java/com/goldmen/home/user/member/dto/request/MemberUpdateRequest.java
- goldmen-application/goldmen-api/src/main/java/com/goldmen/home/user/member/service/MemberService.java
- goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/user/member/domain/Member.java
- goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/user/member/service/MemberModifyService.java
- goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/user/member/service/MemberServiceImpl.java
> 회원 정보 수정 기능 구현

- goldmen-application/goldmen-api/src/main/java/com/goldmen/home/user/member/controller/MemberController.java
- goldmen-application/goldmen-api/src/main/java/com/goldmen/home/user/member/dto/request/MemberDeleteRequest.java
- goldmen-application/goldmen-api/src/main/java/com/goldmen/home/user/member/service/MemberService.java
- goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/user/member/service/MemberModifyService.java
- goldmen-domain/jpa-domain/src/main/java/com/goldmen/home/user/member/service/MemberServiceImpl.java
회원 탈퇴 기능 구현
resolve #59
---
---
---
> 회원 탈퇴 기능 구현
